<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';

type Match={methods:string[];path:string;pathPrefix:string};
type Rule={id:string;name:string;enabled:boolean;priority:number;match:Match;target:string;pathPrefix:string};
type Route={id:string;name:string;group:string;enabled:boolean;host:string;target:string;preserveHost:boolean;rules:Rule[]};
type Config={version:number;listener:{address:string;port:number};routes:Route[]};
type RequestEvent={id:number;time:string;method:string;host:string;path:string;target:string;routeId:string;ruleId?:string;status:number;durationMs:number;error?:string};

async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/${path}`,init);if(!response.ok)throw new Error(await response.text());return response.json()}
const GetConfig=()=>api<Config>('config');const SaveConfig=(value:Config)=>api('config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const Status=()=>api<any>('status');const Requests=()=>api<RequestEvent[]>('requests');const Start=()=>api('start',{method:'POST'});const Stop=()=>api('stop',{method:'POST'});const ClearRequests=()=>api('requests/clear',{method:'POST'});const Quit=()=>api('quit',{method:'POST'});const Meta=()=>api<{version:string;configPath:string}>('meta');

const page=ref<'routes'|'requests'|'settings'>('routes');const config=reactive<Config>({version:2,listener:{address:'127.0.0.1',port:80},routes:[]});
const status=reactive({running:false,listen:'',lastError:''});const requests=ref<RequestEvent[]>([]);const selected=ref<Route|null>(null);const error=ref('');const dirty=ref(false);const configPath=ref('');const version=ref('');const query=ref('');const groupFilter=ref('');
const groups=computed(()=>[...new Set(config.routes.map(r=>r.group).filter(Boolean))].sort((a,b)=>a.localeCompare(b)));
const visibleRoutes=computed(()=>config.routes.filter(r=>(!groupFilter.value||r.group===groupFilter.value)&&`${r.name} ${r.host} ${r.target} ${r.group}`.toLowerCase().includes(query.value.toLowerCase())));
const enabledCount=computed(()=>config.routes.filter(r=>r.enabled).length);const visibleRequests=computed(()=>requests.value.slice().reverse());
function slug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`route-${Date.now()}`}
function newRoute():Route{return{id:`route-${Date.now()}`,name:'新路由',group:'',enabled:true,host:'',target:'http://127.0.0.1:3000',preserveHost:true,rules:[]}}
function newRule():Rule{return{id:`rule-${Date.now()}`,name:'新规则',enabled:true,priority:100,match:{methods:[],path:'',pathPrefix:'/api'},target:'http://127.0.0.1:9000',pathPrefix:''}}
function addRoute(){const route=newRoute();config.routes.push(route);edit(route);changed()}
function edit(route:Route){selected.value=route}function changed(){dirty.value=true}
function routeName(id:string){return config.routes.find(r=>r.id===id)?.name||id}
function removeRoute(route:Route){if(confirm(`删除 ${route.name}？`)){config.routes=config.routes.filter(r=>r!==route);selected.value=null;changed()}}
async function load(){try{error.value='';Object.assign(config,await GetConfig() as Config);config.routes.forEach(r=>{r.group||='';r.rules||=[];r.rules.forEach(x=>{x.match.methods||=[];x.match.path||='';x.match.pathPrefix||='';x.pathPrefix||=''})});dirty.value=false}catch(e){error.value=String(e)}}
async function save(){try{error.value='';await SaveConfig(config);dirty.value=false;await refresh()}catch(e){error.value=String(e)}}
async function refresh(){Object.assign(status,await Status())}
async function toggle(){try{if(dirty.value)await save();status.running?await Stop():await Start();await refresh()}catch(e){error.value=String(e)}}
async function clearLog(){await ClearRequests();requests.value=[]}
onMounted(async()=>{try{const meta=await Meta();configPath.value=meta.configPath;version.value=meta.version;await Promise.all([load(),refresh(),Requests().then(x=>requests.value=x??[])]);setInterval(refresh,1500);setInterval(async()=>{requests.value=(await Requests())??[]},1000)}catch(e){error.value=String(e)}});
</script>

<template><div class="shell"><aside><div class="brand"><b>LR</b><div><strong>LocalRoute</strong><small>Development Router</small></div></div><nav><button :class="{active:page==='routes'}" @click="page='routes'">路由管理</button><button :class="{active:page==='requests'}" @click="page='requests'">请求日志 <i v-if="requests.length">{{requests.length}}</i></button><button :class="{active:page==='settings'}" @click="page='settings'">设置</button></nav><footer>LocalRoute {{version}}<span>macOS · Windows</span></footer></aside>
<main><header><div><p>LOCAL DEVELOPMENT PROXY</p><h1>{{page==='routes'?'路由管理':page==='requests'?'请求日志':'设置'}}</h1></div><div class="run"><span :class="['pill',{on:status.running}]"><i></i>{{status.running?'运行中':'已停止'}}</span><button class="primary" @click="toggle">{{status.running?'停止代理':'启动代理'}}</button></div></header><div v-if="error||status.lastError" class="error">{{error||status.lastError}}</div>

<template v-if="page==='routes'"><section class="stats"><article><span>监听地址</span><b>{{config.listener.address}}:{{config.listener.port}}</b></article><article><span>启用路由</span><b>{{enabledCount}}</b></article><article><span>规则数量</span><b>{{config.routes.reduce((n,r)=>n+r.rules.length,0)}}</b></article></section><section class="panel"><div class="toolbar"><div class="route-filters"><input v-model="query" placeholder="搜索名称、域名或目标"><select v-model="groupFilter"><option value="">全部分组</option><option v-for="group in groups" :key="group" :value="group">{{group}}</option></select></div><button class="secondary" @click="addRoute">＋ 添加路由</button></div><table><thead><tr><th>启用</th><th>名称</th><th>域名</th><th>目标</th><th>规则</th></tr></thead><tbody><tr v-for="route in visibleRoutes" :key="route.id" @click="edit(route)"><td><input type="checkbox" v-model="route.enabled" @change.stop="changed"></td><td><b>{{route.name}}</b><small>{{route.group||'未分组'}}</small></td><td><code>{{route.host}}</code></td><td><code>{{route.target}}</code></td><td><span class="count">{{route.rules.length}}</span></td></tr></tbody></table><div v-if="!visibleRoutes.length" class="empty">还没有匹配的路由</div></section><div class="savebar"><span>{{dirty?'有未保存的修改':'配置已保存'}}</span><button class="primary" :disabled="!dirty" @click="save">保存并应用</button></div></template>

<template v-else-if="page==='requests'"><section class="panel"><div class="toolbar"><div><b>最近请求</b><small>内存中最多保留 1000 条，不记录请求体与响应体。</small></div><button class="secondary" @click="clearLog">清空</button></div><table><thead><tr><th>时间</th><th>方法</th><th>Host / Path</th><th>目标</th><th>状态</th><th>耗时</th></tr></thead><tbody><tr v-for="r in visibleRequests" :key="r.id"><td>{{new Date(r.time).toLocaleTimeString()}}</td><td><b>{{r.method}}</b></td><td><code>{{r.host}}{{r.path}}</code><small>{{routeName(r.routeId)}}<template v-if="r.ruleId"> · 规则 {{r.ruleId}}</template></small></td><td><code>{{r.target}}</code></td><td><span :class="['http',r.status>=400?'bad':'good']">{{r.status}}</span></td><td>{{r.durationMs}} ms</td></tr></tbody></table><div v-if="!requests.length" class="empty">代理请求会实时显示在这里</div></section></template>

<template v-else><section class="panel settings"><h2>监听设置</h2><label>监听地址<input v-model="config.listener.address" @input="changed"></label><label>端口<input type="number" min="1" max="65535" v-model="config.listener.port" @input="changed"></label><p>监听地址修改后，需要停止并重新启动代理。</p><h2>配置文件</h2><code class="path">{{configPath}}</code><p>路由配置使用 YAML v2，可由 GUI 或文本编辑器维护。</p><h2>窗口行为</h2><p>关闭主窗口会隐藏应用并保持代理运行。再次启动 LocalRoute 会唤醒已有窗口。</p><div class="settings-actions"><button class="primary" :disabled="!dirty" @click="save">保存设置</button><button class="danger" @click="Quit">退出 LocalRoute</button></div></section></template></main>

<div v-if="selected" class="backdrop" @click.self="selected=null"><section class="drawer"><header><div><small>ROUTE EDITOR</small><h2>{{selected.name||'编辑路由'}}</h2></div><button @click="selected=null">×</button></header><div class="form"><label>名称<input v-model="selected.name" @input="changed"></label><label>分组<input v-model="selected.group" list="route-groups" placeholder="未分组" @input="changed"><datalist id="route-groups"><option v-for="group in groups" :key="group" :value="group"></option></datalist></label><label>请求域名<input v-model="selected.host" @input="changed"></label><label>默认目标<input v-model="selected.target" @input="changed"></label><label class="check"><input type="checkbox" v-model="selected.preserveHost" @change="changed"> 保留请求 Host</label><div class="rules-head"><h3>条件规则</h3><button @click="selected.rules.push(newRule());changed()">＋ 添加</button></div><article class="rule" v-for="(rule,index) in selected.rules" :key="rule.id"><div><input type="checkbox" v-model="rule.enabled" @change="changed"><input v-model="rule.name" placeholder="规则名称" @input="changed"><button @click="selected.rules.splice(index,1);changed()">×</button></div><label>路径前缀<input v-model="rule.match.pathPrefix" @input="rule.match.path='';changed()"></label><label>精确路径<input v-model="rule.match.path" @input="rule.match.pathPrefix='';changed()"></label><label>目标<input v-model="rule.target" @input="changed"></label></article><details class="advanced"><summary>高级设置</summary><label>路由 ID<input v-model="selected.id" @change="selected.id=slug(selected.id);changed()"></label><p>用于日志和程序内部引用，通常不需要修改。</p></details></div><footer><button class="danger" @click="removeRoute(selected)">删除路由</button><button class="primary" @click="selected=null">完成</button></footer></section></div></div></template>
